#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

echo "Running blockMesh application"
runApplication blockMesh

runApplication decomposePar

echo "Running viscoelasticFluidFoam solver"
echo "Feta-PTT model: "
runParallel $application

runApplication reconstructPar

echo "done!"
