#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

echo "Running blockMesh application"
runApplication blockMesh

runApplication decomposePar

echo "Running viscoelasticFluidFoam solver"
echo "DCPP model: execution time ~ 41830 s in a Core 2 Duo 2.0 Ghz processor"
runParallel $application
 
runApplication reconstructPar

echo "done!"
